### ISSUE TITLE
Anaconda Cloud Developer Install: missing module 'packaging'

### ISSUE THREAD

**Issue by dsbarker** [labscript-suite/labscript-suite#58]
I'm not sure that this is the best place to open this issue, so please redirect me as necessary.

After following the instructions at https://docs.labscriptsuite.org/en/stable/installation/developer-anaconda/, running lyse from anaconda prompt yields:
```
(py38) >lyse
Traceback (most recent call last):
  File "c:\users\cavslab\labscript-suite\lyse\lyse\__main__.py", line 2, in <module>
    import labscript_utils.excepthook
  File "c:\users\cavslab\labscript-suite\labscript-utils\labscript_utils\__init__.py", line 50, in <module>
    from labscript_utils.versions import VersionException, check_version
  File "c:\users\cavslab\labscript-suite\labscript-utils\labscript_utils\versions.py", line 19, in <module>
    import packaging.version
ModuleNotFoundError: No module named 'packaging'
```
The issue is fixed with ```conda install packaging```. Apparently, the 'packaging' module is not downloaded by default when making a new python 3.8 environment (at least on my machine). This issue obviously isn't serious, but perhaps the documentation or requirements should be updated  to ensure that users install 'packaging' before running
```
(py38) > pip install --no-build-isolation --no-deps ^
         -e labscript -e runmanager -e blacs -e lyse ^
         -e runviewer -e labscript-devices -e labscript-utils
```

**Comment by philipstarkey** [comment]
Did you run `setuptools-conda install-requirements labscript runmanager blacs lyse runviewer labscript-devices labscript-utils` prior to calling pip install? That should have installed the packaging dependency (as it's a dependency of labscript-utils). It's a new dependency though so potentially something has gone wrong in how we added it.

**Comment by dsbarker** [comment]
Yes, I ran that command.
