### ISSUE TITLE
Double error when compiling runmanager labscript file

### ISSUE THREAD

**Issue by manuelmorgado** [labscript-suite/labscript-suite#66]
Hello, 

I just started with Labscript using Ubuntu (18.04), but I have find some error just when Engage from Run manager:

```
Loading default config file /home/user/labscript-suite/app_saved_configs/example_apparatus/runmanager/runmanager.ini...done.
Ready.

t = 0.000000000 s: Start
t = 1.000000000 s: Toggle digital_out (high)
t = 1.750000000 s: Toggle digital_out (low)
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/qlab-env/lib/python3.8/site-packages/labscript/labscript.py", line 3193, in _file_watcher_callback
    _vcs_cache[name] = _run_vcs_commands(name)
  File "/home/user/anaconda3/envs/qlab-env/lib/python3.8/site-packages/labscript/labscript.py", line 3247, in _run_vcs_commands
    process = subprocess.Popen(
  File "/home/user/anaconda3/envs/qlab-env/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/user/anaconda3/envs/qlab-env/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hg'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/qlab-env/lib/python3.8/site-packages/runmanager/batch_compiler.py", line 72, in compile
    exec(code, self.script_module.__dict__)
  File "/home/user/labscript-suite/userlib/labscriptlib/example_apparatus/example_experiment.py", line 48, in <module>
    stop(t)
  File "/home/user/anaconda3/envs/qlab-env/lib/python3.8/site-packages/labscript/labscript.py", line 3588, in stop
    generate_code()
  File "/home/user/anaconda3/envs/qlab-env/lib/python3.8/site-packages/labscript/labscript.py", line 3413, in generate_code
    save_labscripts(hdf5_file)
  File "/home/user/anaconda3/envs/qlab-env/lib/python3.8/site-packages/labscript/labscript.py", line 3309, in save_labscripts
    except WindowsError if os.name == 'nt' else None:
TypeError: catching classes that do not inherit from BaseException is not allowed
Compilation aborted.
```

Also when recompile Connection Table in blacs:

```
Recompiling connection table
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/qlab-env/lib/python3.8/site-packages/labscript/labscript.py", line 3193, in _file_watcher_callback
    _vcs_cache[name] = _run_vcs_commands(name)
  File "/home/user/anaconda3/envs/qlab-env/lib/python3.8/site-packages/labscript/labscript.py", line 3247, in _run_vcs_commands
    process = subprocess.Popen(
  File "/home/user/anaconda3/envs/qlab-env/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/user/anaconda3/envs/qlab-env/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/qlab-env/lib/python3.8/site-packages/runmanager/batch_compiler.py", line 72, in compile
    exec(code, self.script_module.__dict__)
  File "/home/user/labscript-suite/userlib/labscriptlib/example_apparatus/connection_table.py", line 27, in <module>
    stop(1.0)
  File "/home/user/anaconda3/envs/qlab-env/lib/python3.8/site-packages/labscript/labscript.py", line 3588, in stop
    generate_code()
  File "/home/user/anaconda3/envs/qlab-env/lib/python3.8/site-packages/labscript/labscript.py", line 3413, in generate_code
    save_labscripts(hdf5_file)
  File "/home/user/anaconda3/envs/qlab-env/lib/python3.8/site-packages/labscript/labscript.py", line 3309, in save_labscripts
    except WindowsError if os.name == 'nt' else None:
TypeError: catching classes that do not inherit from BaseException is not allowed
Compilation failed. Please fix the errors in the connection table (python file) and try again
```

Seems a problem recognizing the OS ?

**Comment by manuelmorgado** [comment]
A tricky solution that it seems to work for me: install mercurial with 

pip install mercurial

(https://github.com/frej/fast-export/)

**Comment by chrisjbillington** [comment]
Thanks for the bug report. Better behaviour when mercurial isn't installed would obviously be preferable, it looks like there is some exception handling there for it, but it might be Windows-specific or otherwise incorrect (Python doesn't like "except None" - looks like it used to in Python 2, but no longer in Python 3).

You may also disable saving of mercurial info in your labconfig file, by setting save_hg_info False in the following section (defaults shown below):
```
[labscript]
save_hg_info = True
save_git_info = False
```

Fewer labscript suite users use Linux than Windows, so there may be other issues like this may be easily fixed but that we're not aware of. Please do report any other issues that you encounter!

**Comment by chrisjbillington** [comment]
This should be fixed in https://github.com/labscript-suite/labscript/pull/86

**Comment by manuelmorgado** [comment]
Thank you @chrisjbillington !  I will check my labconfig file. 

I will do it for sure ;)
